import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

// ─── Helper: generate doctor data ───────────────────────────────────────────

interface DoctorSeed {
	name: string;
	specialization: string;
	qualification: string;
	experienceYears: number;
	consultationFee: number;
	rating: number;
	city: string;
	state: string;
	bio: string;
	contactInfo: string;
	phone: string;
	isAvailable: boolean;
}

const specializations = [
	"General Physician",
	"Cardiologist",
	"Dermatologist",
	"Orthopedic Surgeon",
	"Gynecologist",
	"Pediatrician",
	"Neurologist",
	"ENT Specialist",
	"Ophthalmologist",
	"Psychiatrist",
	"Dentist",
	"Gastroenterologist",
	"Urologist",
	"Pulmonologist",
	"Endocrinologist",
	"Nephrologist",
	"Oncologist",
	"Rheumatologist",
	"General Surgeon",
	"Physiotherapist",
];

const bioVariants: Record<string, string[]> = {
	"General Physician": [
		"Experienced general physician providing comprehensive primary care and preventive medicine.",
		"Dedicated family doctor with a patient-first approach to primary healthcare and chronic disease management.",
		"Skilled general practitioner specializing in holistic wellness, routine check-ups, and lifestyle counseling.",
		"Compassionate physician offering personalized treatment plans for acute and chronic medical conditions.",
		"Board-certified physician focused on evidence-based primary care and health screening.",
		"Primary care physician experienced in managing lifestyle diseases and preventive health screening.",
		"Trusted family physician providing long-term care for diabetes, hypertension, and infections.",
		"General medicine specialist focused on early diagnosis and patient education.",
		"Physician dedicated to community health and chronic disease prevention.",
		"Holistic care doctor emphasizing nutrition, exercise, and preventive medicine.",
	],
	Cardiologist: [
		"Specialist in cardiovascular diseases with expertise in interventional cardiology and heart failure management.",
		"Heart specialist with deep expertise in echocardiography, angioplasty, and cardiac rehabilitation.",
		"Interventional cardiologist performing complex coronary procedures and managing arrhythmias.",
		"Expert in preventive cardiology, lipid management, and hypertension control.",
		"Cardiac specialist skilled in pacemaker implantation, stent placement, and post-bypass care.",
		"Cardiology consultant specializing in coronary artery disease and heart rhythm disorders.",
		"Expert in non-invasive cardiology including stress testing and cardiac imaging.",
		"Preventive cardiologist helping patients reduce cardiovascular risk factors.",
		"Heart failure specialist managing advanced cardiac conditions.",
		"Clinical cardiologist experienced in complex cardiac diagnostics.",
	],
	Dermatologist: [
		"Expert in clinical and cosmetic dermatology treating skin, hair, and nail conditions.",
		"Skin specialist offering advanced treatments for acne, eczema, psoriasis, and vitiligo.",
		"Dermatologist with expertise in cosmetic procedures including laser therapy and chemical peels.",
		"Clinical dermatologist focused on skin cancer screening, mole mapping, and surgical dermatology.",
		"Experienced dermatologist providing holistic skincare solutions and anti-aging treatments.",
		"Dermatology expert treating chronic skin disorders and cosmetic concerns.",
		"Skin care specialist offering medical and aesthetic dermatology services.",
		"Dermatologist focused on hair loss, pigmentation, and chronic dermatitis.",
		"Cosmetic dermatology practitioner using lasers and injectables.",
		"Clinical skin specialist managing autoimmune skin diseases.",
	],
	"Orthopedic Surgeon": [
		"Skilled orthopedic surgeon specializing in joint replacements and sports injury management.",
		"Bone and joint specialist with expertise in arthroscopy, fracture fixation, and spinal surgery.",
		"Orthopedic surgeon experienced in minimally invasive techniques and ligament reconstruction.",
		"Sports medicine specialist treating athletic injuries, ACL tears, and rotator cuff repair.",
		"Expert in total hip and knee replacement surgery with excellent patient outcomes.",
		"Orthopedic consultant treating trauma, fractures, and degenerative joint diseases.",
		"Joint preservation specialist with expertise in cartilage repair.",
		"Orthopedic trauma surgeon handling complex fracture reconstruction.",
		"Spine and joint surgeon specializing in minimally invasive procedures.",
		"Musculoskeletal surgeon focused on mobility restoration.",
	],
	Gynecologist: [
		"Dedicated gynecologist with expertise in women's health, reproductive medicine, and prenatal care.",
		"Women's health specialist offering comprehensive obstetric and gynecological care for all ages.",
		"Experienced in high-risk pregnancy management, laparoscopic surgery, and fertility counseling.",
		"Gynecologist specializing in PCOS management, menstrual disorders, and minimally invasive surgery.",
		"Compassionate OB-GYN providing personalized maternal care from conception through postpartum.",
		"Women's health expert specializing in fertility and reproductive endocrinology.",
		"Gynecologist focused on adolescent and menopausal health.",
		"Obstetrician experienced in painless delivery and prenatal diagnostics.",
		"Laparoscopic gynecologic surgeon treating fibroids and endometriosis.",
		"Reproductive health specialist providing comprehensive female care.",
	],
	Pediatrician: [
		"Compassionate pediatrician focused on child development, vaccinations, and childhood illnesses.",
		"Child health specialist providing newborn care, growth monitoring, and adolescent medicine.",
		"Pediatrician experienced in managing childhood asthma, allergies, and nutritional guidance.",
		"Dedicated children's doctor offering preventive healthcare and developmental assessment.",
		"Expert in neonatal care, immunization planning, and childhood infectious diseases.",
		"Child specialist focused on preventive pediatrics and growth monitoring.",
		"Pediatric consultant experienced in neonatal and infant care.",
		"Children's doctor managing developmental and behavioral disorders.",
		"Pediatric healthcare provider emphasizing vaccination and nutrition.",
		"Infant and child specialist treating acute pediatric illnesses.",
	],
	Neurologist: [
		"Neurologist specializing in diagnosis and treatment of brain, spinal cord, and nerve disorders.",
		"Brain and nerve specialist with expertise in epilepsy management, stroke care, and headache disorders.",
		"Clinical neurologist experienced in Parkinson's disease, multiple sclerosis, and neuromuscular conditions.",
		"Specialist in neurodiagnostics including EEG, EMG, and advanced brain imaging interpretation.",
		"Expert neurologist providing comprehensive care for dementia, neuropathy, and movement disorders.",
		"Neurology consultant specializing in stroke prevention and rehabilitation.",
		"Brain specialist treating seizures, neuropathy, and neurodegeneration.",
		"Clinical neurologist focused on chronic neurological disorders.",
		"Neurophysiology expert interpreting advanced neural diagnostics.",
		"Neurologist experienced in cognitive and memory disorders.",
	],
	"ENT Specialist": [
		"ENT specialist treating ear, nose, and throat conditions including sinus and hearing disorders.",
		"Head and neck surgeon skilled in tonsillectomy, septoplasty, and cochlear implant evaluation.",
		"Otolaryngologist managing chronic sinusitis, vertigo, sleep apnea, and voice disorders.",
		"ENT surgeon with expertise in endoscopic nasal surgery and pediatric ENT conditions.",
		"Specialist in hearing loss management, tinnitus treatment, and allergy-related ENT problems.",
	],
	Ophthalmologist: [
		"Eye care specialist providing comprehensive vision care including cataract and glaucoma treatment.",
		"Ophthalmic surgeon skilled in LASIK, cataract removal, and retinal detachment repair.",
		"Eye specialist with expertise in diabetic retinopathy, macular degeneration, and corneal transplant.",
		"Comprehensive eye doctor offering pediatric eye care, squint correction, and contact lens fitting.",
		"Glaucoma and retina specialist providing advanced surgical and laser-based treatments.",
	],
	Psychiatrist: [
		"Mental health professional providing therapy and medication management for psychiatric conditions.",
		"Psychiatrist specializing in anxiety disorders, depression, OCD, and bipolar disorder management.",
		"Expert in cognitive behavioral therapy, psychopharmacology, and stress management techniques.",
		"Child and adolescent psychiatrist offering counseling for ADHD, autism, and behavioral issues.",
		"Addiction psychiatrist experienced in substance abuse recovery and dual-diagnosis treatment.",
		"Mental health specialist providing psychotherapy and medication management.",
		"Psychiatric consultant treating mood, anxiety, and personality disorders.",
		"Behavioral health expert focusing on stress and trauma recovery.",
		"Psychiatrist specializing in sleep and psychosomatic disorders.",
		"Clinical psychiatrist supporting emotional and psychological wellbeing.",
	],
	Dentist: [
		"General dentist offering preventive, restorative, and cosmetic dental care for all ages.",
		"Dental surgeon experienced in root canal treatment, dental implants, and orthodontic correction.",
		"Cosmetic dentist specializing in teeth whitening, veneers, and smile makeover procedures.",
		"Family dentist providing gentle dental care, gum treatment, and wisdom tooth extraction.",
		"Pediatric-friendly dentist focused on cavity prevention, fluoride treatment, and oral hygiene education.",
		"Oral health specialist focused on preventive and restorative dentistry.",
		"Dental practitioner providing advanced prosthetic and implant care.",
		"Smile design expert offering aesthetic dental solutions.",
		"Dentist experienced in periodontal and gum disease treatment.",
		"Comprehensive dental care provider for families.",
	],
	Gastroenterologist: [
		"Specialist in digestive system disorders including liver, stomach, and intestinal conditions.",
		"GI specialist experienced in endoscopy, colonoscopy, and inflammatory bowel disease management.",
		"Hepatologist managing hepatitis, fatty liver disease, and cirrhosis with evidence-based protocols.",
		"Expert in acid reflux, peptic ulcers, IBS, and gastrointestinal motility disorders.",
		"Gastroenterologist skilled in advanced endoscopic procedures and pancreatic disorder management.",
	],
	Urologist: [
		"Urologist treating urinary tract disorders and male reproductive health conditions.",
		"Specialist in kidney stones, prostate disorders, and minimally invasive urological surgery.",
		"Uro-oncologist with expertise in bladder cancer, renal tumors, and robotic-assisted surgery.",
		"Expert in pediatric urology, urinary incontinence, and erectile dysfunction management.",
		"Urological surgeon skilled in laser lithotripsy, TURP, and reconstructive urology.",
	],
	Pulmonologist: [
		"Lung specialist treating respiratory diseases including asthma, COPD, and pulmonary infections.",
		"Chest physician with expertise in bronchoscopy, sleep studies, and critical care pulmonology.",
		"Respiratory medicine specialist managing tuberculosis, interstitial lung disease, and lung fibrosis.",
		"Expert in allergy-induced asthma, occupational lung disease, and pulmonary rehabilitation.",
		"Pulmonologist specializing in post-COVID recovery, pneumonia management, and ventilator weaning.",
	],
	Endocrinologist: [
		"Specialist in hormonal disorders including diabetes, thyroid, and metabolic conditions.",
		"Diabetes specialist providing insulin management, HbA1c optimization, and dietary counseling.",
		"Thyroid expert treating hypothyroidism, hyperthyroidism, and thyroid nodules with precision.",
		"Endocrinologist managing PCOS, adrenal disorders, pituitary conditions, and osteoporosis.",
		"Expert in pediatric endocrinology, growth disorders, and childhood diabetes management.",
	],
	Nephrologist: [
		"Kidney specialist providing care for chronic kidney disease and dialysis management.",
		"Renal specialist experienced in kidney transplant evaluation, hemodialysis, and peritoneal dialysis.",
		"Nephrologist managing hypertensive nephropathy, glomerulonephritis, and electrolyte disorders.",
		"Expert in diabetic kidney disease prevention and early-stage CKD intervention.",
		"Kidney specialist skilled in renal biopsy interpretation and transplant immunosuppression.",
	],
	Oncologist: [
		"Cancer specialist providing comprehensive oncology care including chemotherapy and targeted therapy.",
		"Medical oncologist experienced in breast cancer, lung cancer, and immunotherapy protocols.",
		"Expert in palliative oncology, pain management, and supportive cancer care.",
		"Surgical oncologist performing tumor resection, lymph node dissection, and reconstructive procedures.",
		"Oncologist specializing in hematologic malignancies, lymphoma, and bone marrow transplant care.",
	],
	Rheumatologist: [
		"Specialist in autoimmune and inflammatory conditions including arthritis and lupus.",
		"Rheumatologist treating rheumatoid arthritis, ankylosing spondylitis, and gout with biologic therapies.",
		"Expert in connective tissue disorders, vasculitis, and fibromyalgia management.",
		"Autoimmune disease specialist providing comprehensive care for scleroderma and Sjögren's syndrome.",
		"Rheumatologist with expertise in joint injections, DMARDs management, and musculoskeletal ultrasound.",
	],
	"General Surgeon": [
		"Experienced surgeon performing abdominal, laparoscopic, and emergency surgical procedures.",
		"General surgeon skilled in hernia repair, appendectomy, cholecystectomy, and trauma surgery.",
		"Minimally invasive surgeon specializing in laparoscopic and robotic-assisted procedures.",
		"Surgical specialist providing wound care, abscess drainage, and minor surgical procedures.",
		"Expert in bariatric surgery, thyroidectomy, and breast surgical oncology.",
	],
	Physiotherapist: [
		"Licensed physiotherapist specializing in rehabilitation, pain management, and mobility restoration.",
		"Sports physiotherapist providing injury rehabilitation, taping techniques, and strength conditioning.",
		"Neuro-physiotherapist experienced in stroke rehabilitation, spinal cord injury, and balance training.",
		"Orthopedic physiotherapist offering post-surgical rehab, joint mobilization, and ergonomic assessment.",
		"Pediatric physiotherapist focused on developmental delays, cerebral palsy, and motor skill training.",
	],
};

const qualificationVariants: Record<string, string[]> = {
	"General Physician": [
		"MBBS, MD - Internal Medicine",
		"MBBS, MD - General Medicine",
		"MBBS, DNB - Family Medicine",
		"MBBS, MRCP",
		"MBBS, FCPS - General Medicine",
		"MBBS, MD - Community Medicine",
		"MBBS, PGDGM",
		"MBBS, Diploma in Family Medicine",
		"MBBS, MD - Preventive & Social Medicine",
		"MBBS, Fellowship in Primary Care",
		"MBBS, MD - Internal Medicine, FICP",
		"MBBS, DNB - General Medicine",
		"MBBS, MD - Medicine",
		"MBBS, Fellowship in Geriatric Medicine",
		"MBBS, MD - Internal Medicine, FRCP",
	],

	Cardiologist: [
		"MBBS, MD - Medicine, DM - Cardiology",
		"MBBS, MD - Cardiology, FACC",
		"MBBS, DNB - Cardiology, FESC",
		"MBBS, MD, DM - Interventional Cardiology",
		"MBBS, MRCP, CCT - Cardiology",
		"MBBS, MD - Medicine, Fellowship in Cardiology",
		"MBBS, DNB - Cardiology",
		"MBBS, MD, DM - Clinical Cardiology",
		"MBBS, MD - Medicine, DM - Cardiology, FSCAI",
		"MBBS, MRCP, FRCP - Cardiology",
		"MBBS, DM - Cardiology",
		"MBBS, MD - Medicine, Fellowship in Electrophysiology",
		"MBBS, MD, DM - Cardiology, FCSI",
		"MBBS, MD - Medicine, DM - Cardiology, FESC",
		"MBBS, MD - Cardiology",
	],

	Dermatologist: [
		"MBBS, MD - Dermatology, Venereology & Leprosy",
		"MBBS, DVD, MD - Dermatology",
		"MBBS, DNB - Dermatology",
		"MBBS, DDVL",
		"MBBS, MD - Skin & VD, FRCP",
		"MBBS, MD - Dermatology, Fellowship in Aesthetic Medicine",
		"MBBS, DNB - Dermatology, Venereology & Leprosy",
		"MBBS, MD - Dermatosurgery",
		"MBBS, Diploma in Dermatology",
		"MBBS, MD - Dermatology, Fellowship in Cosmetology",
		"MBBS, DDVL, Fellowship in Trichology",
		"MBBS, MD - Dermatology, FAAD",
		"MBBS, MD - Skin & VD",
		"MBBS, DNB - Skin & VD",
		"MBBS, MD - Dermatology, Fellowship in Lasers",
	],

	"Orthopedic Surgeon": [
		"MBBS, MS - Orthopaedics",
		"MBBS, DNB - Orthopedics, FICS",
		"MBBS, MS - Ortho, MCh - Joint Replacement",
		"MBBS, D.Ortho, MS - Orthopedics",
		"MBBS, MS - Orthopaedics, FRCS",
		"MBBS, MS - Orthopaedics, Fellowship in Arthroscopy",
		"MBBS, DNB - Orthopedics",
		"MBBS, MS - Ortho, Fellowship in Spine Surgery",
		"MBBS, MS - Orthopaedics, AO Fellowship",
		"MBBS, MS - Orthopaedics, Fellowship in Trauma",
		"MBBS, MS - Orthopaedics, Fellowship in Joint Replacement",
		"MBBS, DNB - Orthopedics, Fellowship in Sports Injury",
		"MBBS, MS - Orthopaedics, MCh - Orthopedics",
		"MBBS, MS - Orthopaedics, FIJR",
		"MBBS, MS - Orthopaedics, FIAS",
	],

	Gynecologist: [
		"MBBS, DGO, MD - Obstetrics & Gynecology",
		"MBBS, MS - OBG, DNB",
		"MBBS, MD - OBG, FRCOG",
		"MBBS, DGO, FICOG",
		"MBBS, DNB - Obstetrics & Gynecology",
		"MBBS, MD - Obstetrics & Gynecology",
		"MBBS, MS - Obstetrics & Gynecology",
		"MBBS, DGO, Fellowship in IVF",
		"MBBS, MD - OBG, Fellowship in Laparoscopy",
		"MBBS, MS - OBG, FMAS",
		"MBBS, DNB - OBG, MRCOG",
		"MBBS, MD - OBG, FICMCH",
		"MBBS, MS - OBG, Fellowship in Reproductive Medicine",
		"MBBS, DGO, Diploma in Reproductive Medicine",
		"MBBS, MD - OBG, Fellowship in Fetal Medicine",
	],

	Pediatrician: [
		"MBBS, DCH, MD - Pediatrics",
		"MBBS, MD - Pediatrics, IAP Fellow",
		"MBBS, DNB - Pediatrics",
		"MBBS, DCH, MRCPCH",
		"MBBS, MD - Pediatrics, FIAP",
		"MBBS, MD - Pediatrics",
		"MBBS, Diploma in Child Health",
		"MBBS, DNB - Pediatrics, Fellowship in Neonatology",
		"MBBS, MD - Pediatrics, Fellowship in Pediatric ICU",
		"MBBS, DCH, Fellowship in Neonatal Care",
		"MBBS, MD - Pediatrics, Fellowship in Pediatric Neurology",
		"MBBS, DNB - Pediatrics, MNAMS",
		"MBBS, MD - Pediatrics, Fellowship in Developmental Pediatrics",
		"MBBS, DCH, Fellowship in Pediatric Cardiology",
		"MBBS, MD - Pediatrics, Fellowship in Adolescent Medicine",
	],

	Neurologist: [
		"MBBS, MD - Medicine, DM - Neurology",
		"MBBS, DNB - Neurology",
		"MBBS, MD, DM - Neurology, FRCP",
		"MBBS, MRCP, CCT - Neurology",
		"MBBS, MD - Neurology, Fellowship in Epilepsy",
		"MBBS, DM - Neurology",
		"MBBS, MD - Medicine, DM - Neurology",
		"MBBS, DNB - Neurology, Fellowship in Stroke",
		"MBBS, MD - Medicine, Fellowship in Neurophysiology",
		"MBBS, DM - Neurology, Fellowship in Movement Disorders",
		"MBBS, MD - Medicine, DM - Neurology, FIAN",
		"MBBS, MRCP, FRCP - Neurology",
		"MBBS, DM - Neurology, Fellowship in Headache",
		"MBBS, MD - Neurology",
		"MBBS, DNB - Neurology, MNAMS",
	],

	"ENT Specialist": [
		"MBBS, MS - ENT",
		"MBBS, DNB - Otorhinolaryngology",
		"MBBS, DLO, MS - ENT",
		"MBBS, MS - ENT, FICS",
		"MBBS, DORL, DNB - ENT",
		"MBBS, MS - ENT, Fellowship in Head & Neck Surgery",
		"MBBS, DNB - ENT",
		"MBBS, MS - ENT, Fellowship in Otology",
		"MBBS, MS - ENT, Fellowship in Rhinology",
		"MBBS, MS - ENT, Fellowship in Laryngology",
		"MBBS, DLO",
		"MBBS, MS - ENT, FRCS",
		"MBBS, DNB - ENT, MNAMS",
		"MBBS, MS - ENT, Fellowship in Skull Base Surgery",
		"MBBS, MS - ENT, Fellowship in Cochlear Implant",
	],

	Ophthalmologist: [
		"MBBS, MS - Ophthalmology",
		"MBBS, DO, DNB - Ophthalmology",
		"MBBS, MS - Ophthalmology, FRCS",
		"MBBS, DOMS, MS - Ophthalmology",
		"MBBS, DNB - Ophthalmology, FICO",
		"MBBS, MS - Ophthalmology, Fellowship in Retina",
		"MBBS, MS - Ophthalmology, Fellowship in Cornea",
		"MBBS, MS - Ophthalmology, Fellowship in Glaucoma",
		"MBBS, DO",
		"MBBS, DNB - Ophthalmology",
		"MBBS, MS - Ophthalmology, Fellowship in Cataract Surgery",
		"MBBS, MS - Ophthalmology, Fellowship in Pediatric Ophthalmology",
		"MBBS, DNB - Ophthalmology, MNAMS",
		"MBBS, MS - Ophthalmology, FICO",
		"MBBS, MS - Ophthalmology, FAICO",
	],

	Psychiatrist: [
		"MBBS, MD - Psychiatry, DPM",
		"MBBS, MD - Psychiatry",
		"MBBS, DNB - Psychiatry",
		"MBBS, DPM, MRCPsych",
		"MBBS, MD - Psychiatry, Fellowship in Addiction Medicine",
		"MBBS, MD - Psychiatry, Fellowship in Child Psychiatry",
		"MBBS, MD - Psychiatry, Fellowship in Geriatric Psychiatry",
		"MBBS, DNB - Psychiatry, MNAMS",
		"MBBS, MD - Psychiatry, FRCPsych",
		"MBBS, MD - Psychiatry, Fellowship in Neuropsychiatry",
		"MBBS, DPM",
		"MBBS, MD - Psychiatry, Fellowship in Psychotherapy",
		"MBBS, DNB - Psychiatry, Fellowship in Deaddiction",
		"MBBS, MD - Psychiatry, Fellowship in Sleep Medicine",
		"MBBS, MD - Psychiatry, Fellowship in Behavioral Medicine",
	],

	Dentist: [
		"BDS, MDS - Conservative Dentistry",
		"BDS, MDS - Prosthodontics",
		"BDS, MDS - Orthodontics",
		"BDS, MDS - Periodontics",
		"BDS, MDS - Oral & Maxillofacial Surgery",
		"BDS, MDS - Endodontics",
		"BDS, MDS - Pedodontics",
		"BDS, MDS - Oral Medicine",
		"BDS, MDS - Public Health Dentistry",
		"BDS, Fellowship in Implantology",
		"BDS, MDS - Prosthodontics & Crown Bridge",
		"BDS, MDS - Oral Pathology",
		"BDS, Fellowship in Cosmetic Dentistry",
		"BDS, MDS - Orthodontics & Dentofacial Orthopedics",
		"BDS, MDS - Periodontology & Implantology",
	],

	Gastroenterologist: [
		"MBBS, MD - Medicine, DM - Gastroenterology",
		"MBBS, DNB - Gastroenterology",
		"MBBS, MD, DM - Hepatology",
		"MBBS, MD - Medicine, DM - GI, FACG",
		"MBBS, MRCP, CCT - Gastroenterology",
		"MBBS, DM - Gastroenterology",
		"MBBS, MD - Medicine, DM - Hepatology",
		"MBBS, DNB - Gastroenterology, MNAMS",
		"MBBS, MD - Medicine, Fellowship in Endoscopy",
		"MBBS, DM - Gastroenterology, Fellowship in Advanced Endoscopy",
		"MBBS, MD - Medicine, DM - Gastroenterology, FASGE",
		"MBBS, MRCP - Gastroenterology",
		"MBBS, MD - Medicine, DM - GI",
		"MBBS, DM - Hepatology",
		"MBBS, MD - Medicine, Fellowship in IBD",
	],

	Urologist: [
		"MBBS, MS - General Surgery, MCh - Urology",
		"MBBS, MS, DNB - Urology",
		"MBBS, MS - Surgery, MCh - Urology, FRCS",
		"MBBS, MS, MCh - Urology, Fellowship in Robotic Surgery",
		"MBBS, DNB - Urology, FICS",
		"MBBS, MCh - Urology",
		"MBBS, MS - Surgery, MCh - Urology",
		"MBBS, DNB - Urology, MNAMS",
		"MBBS, MCh - Urology, Fellowship in Endourology",
		"MBBS, MCh - Urology, Fellowship in Andrology",
		"MBBS, MS - Surgery, MCh - Urology, Fellowship in Robotics",
		"MBBS, DNB - Urology, Fellowship in Uro-oncology",
		"MBBS, MCh - Urology, Fellowship in Pediatric Urology",
		"MBBS, MS - Surgery, MCh - Urology, FACS",
		"MBBS, DNB - Urology",
	],

	Pulmonologist: [
		"MBBS, MD - Pulmonary Medicine",
		"MBBS, DTCD, MD - Chest Medicine",
		"MBBS, DNB - Respiratory Medicine",
		"MBBS, MD - TB & Respiratory Diseases",
		"MBBS, MD - Pulmonology, FCCP",
		"MBBS, MD - Pulmonary Medicine, Fellowship in Critical Care",
		"MBBS, DNB - Pulmonary Medicine",
		"MBBS, MD - Respiratory Medicine",
		"MBBS, MD - Chest Medicine, Fellowship in Sleep Medicine",
		"MBBS, DTCD",
		"MBBS, MD - Pulmonary Medicine, Fellowship in Bronchoscopy",
		"MBBS, MD - Pulmonology, FCCP (USA)",
		"MBBS, DNB - Respiratory Medicine, MNAMS",
		"MBBS, MD - TB & Chest",
		"MBBS, MD - Pulmonary Medicine, Fellowship in Interventional Pulmonology",
	],

	Endocrinologist: [
		"MBBS, MD - Medicine, DM - Endocrinology",
		"MBBS, DNB - Endocrinology",
		"MBBS, MD, DM - Endocrinology, FACE",
		"MBBS, MRCP, CCT - Diabetes & Endocrinology",
		"MBBS, MD - Medicine, Fellowship in Diabetology",
		"MBBS, DM - Endocrinology",
		"MBBS, MD - Medicine, DM - Endocrinology",
		"MBBS, DNB - Endocrinology, MNAMS",
		"MBBS, MD - Medicine, Fellowship in Thyroid Disorders",
		"MBBS, DM - Endocrinology, Fellowship in Diabetes",
		"MBBS, MD - Medicine, DM - Endocrinology, FACP",
		"MBBS, MRCP - Endocrinology",
		"MBBS, MD - Medicine, Fellowship in Metabolism",
		"MBBS, DM - Endocrinology, Fellowship in Pediatric Endocrinology",
		"MBBS, MD - Medicine, DM - Endocrinology, FACE",
	],

	Nephrologist: [
		"MBBS, MD - Medicine, DM - Nephrology",
		"MBBS, DNB - Nephrology",
		"MBBS, MD, DM - Nephrology, FASN",
		"MBBS, MRCP, CCT - Renal Medicine",
		"MBBS, MD - Medicine, DM - Nephrology, Fellowship in Transplant",
		"MBBS, DM - Nephrology",
		"MBBS, MD - Medicine, DM - Nephrology",
		"MBBS, DNB - Nephrology, MNAMS",
		"MBBS, DM - Nephrology, Fellowship in Dialysis",
		"MBBS, MD - Medicine, Fellowship in Transplant Nephrology",
		"MBBS, MRCP - Nephrology",
		"MBBS, MD - Medicine, DM - Nephrology, FISN",
		"MBBS, DM - Nephrology, Fellowship in Critical Care Nephrology",
		"MBBS, MD - Medicine, DM - Renal Medicine",
		"MBBS, DM - Nephrology, Fellowship in Glomerular Diseases",
	],

	Oncologist: [
		"MBBS, MD - Radiotherapy, DM - Oncology",
		"MBBS, MD - Medicine, DM - Medical Oncology",
		"MBBS, MS - Surgery, MCh - Surgical Oncology",
		"MBBS, DNB - Medical Oncology",
		"MBBS, MD, DM - Oncology, ESMO Certification",
		"MBBS, DM - Oncology",
		"MBBS, MD - Oncology",
		"MBBS, MS - Surgery, MCh - Oncology",
		"MBBS, DNB - Oncology, MNAMS",
		"MBBS, MD - Radiotherapy",
		"MBBS, DM - Medical Oncology, Fellowship in Hemato-oncology",
		"MBBS, MS - Surgical Oncology, Fellowship in Oncosurgery",
		"MBBS, MD - Oncology, Fellowship in Chemotherapy",
		"MBBS, DM - Oncology, Fellowship in Immunotherapy",
		"MBBS, MD - Radiotherapy, Fellowship in Radiation Oncology",
	],

	Rheumatologist: [
		"MBBS, MD - Medicine, DM - Rheumatology",
		"MBBS, DNB - Rheumatology",
		"MBBS, MD - Medicine, DM - Clinical Immunology",
		"MBBS, MRCP, CCT - Rheumatology",
		"MBBS, MD - Medicine, Fellowship in Rheumatology",
		"MBBS, DM - Rheumatology",
		"MBBS, MD - Medicine, DM - Rheumatology",
		"MBBS, DNB - Rheumatology, MNAMS",
		"MBBS, MRCP - Rheumatology",
		"MBBS, MD - Medicine, Fellowship in Autoimmune Diseases",
		"MBBS, DM - Clinical Immunology",
		"MBBS, MD - Medicine, Fellowship in Connective Tissue Disorders",
		"MBBS, DM - Rheumatology, Fellowship in Arthritis",
		"MBBS, MD - Medicine, DM - Immunology",
		"MBBS, DM - Rheumatology, Fellowship in Vasculitis",
	],

	"General Surgeon": [
		"MBBS, MS - General Surgery, FMAS",
		"MBBS, MS - General Surgery",
		"MBBS, DNB - General Surgery, FIAGES",
		"MBBS, MS - Surgery, FACS",
		"MBBS, MS - General Surgery, Fellowship in Minimal Access Surgery",
		"MBBS, MS - Surgery",
		"MBBS, DNB - General Surgery",
		"MBBS, MS - General Surgery, Fellowship in Laparoscopy",
		"MBBS, MS - Surgery, Fellowship in GI Surgery",
		"MBBS, MS - Surgery, Fellowship in Colorectal Surgery",
		"MBBS, MS - General Surgery, Fellowship in Hernia Surgery",
		"MBBS, MS - General Surgery, FAIS",
		"MBBS, MS - Surgery, Fellowship in Oncosurgery",
		"MBBS, DNB - General Surgery, MNAMS",
		"MBBS, MS - General Surgery, Fellowship in Bariatric Surgery",
	],

	Physiotherapist: [
		"BPT, MPT",
		"BPT, MPT - Musculoskeletal",
		"BPT, MPT - Neurology",
		"BPT, MPT - Sports Physiotherapy",
		"BPT, MPT - Cardiopulmonary",
		"BPT, MPT - Orthopedics",
		"BPT, MPT - Pediatric Physiotherapy",
		"BPT, MPT - Geriatric Physiotherapy",
		"BPT, MPT - Rehabilitation",
		"BPT, MPT - Neurorehabilitation",
		"BPT, MPT - Manual Therapy",
		"BPT, MPT - Spine Rehabilitation",
		"BPT, MPT - Exercise Therapy",
		"BPT, Fellowship in Sports Rehab",
		"BPT, MPT - Musculoskeletal & Sports",
	],
};

// ─── Punjab Doctors (100) ───────────────────────────────────────────────────

const punjabCities = [
	"Amritsar",
	"Ludhiana",
	"Jalandhar",
	"Patiala",
	"Bathinda",
	"Mohali",
	"Pathankot",
	"Hoshiarpur",
	"Moga",
	"Phagwara",
	"Firozpur",
	"Kapurthala",
	"Sangrur",
	"Barnala",
	"Muktsar",
	"Rupnagar",
	"Nawanshahr",
	"Khanna",
	"Rajpura",
	"Zirakpur",
	"Abohar",
	"Malerkotla",
	"Gobindgarh",
	"Batala",
	"Fazilka",
	"Gurdaspur",
	"Sirhind",
	"Nakodar",
	"Samana",
	"Sunam",
];

const punjabFirstNames = [
	"Harpreet",
	"Gurpreet",
	"Manpreet",
	"Amandeep",
	"Sukhwinder",
	"Simran",
	"Jasleen",
	"Navjot",
	"Kuldeep",
	"Rajinder",
	"Balwinder",
	"Paramjit",
	"Gurbir",
	"Tejinder",
	"Randeep",
	"Amarjeet",
	"Jaswant",
	"Daljit",
	"Maninder",
	"Prabhjot",
	"Gurmeet",
	"Sarabjit",
	"Inderjit",
	"Surjit",
	"Kamalpreet",
	"Ramandeep",
	"Jaspreet",
	"Lovepreet",
	"Gagandeep",
	"Rupinder",
	"Davinder",
	"Bhupinder",
	"Charanjit",
	"Hardeep",
	"Iqbal",
	"Jagtar",
	"Kanwaljit",
	"Lakhbir",
	"Mohinder",
	"Narinder",
	"Onkar",
	"Parvinder",
	"Rashmeet",
	"Satnam",
	"Taranjit",
	"Udham",
	"Varinder",
	"Waheguru",
	"Zorawar",
	"Baljinder",
	"Arshdeep",
	"Gurkirat",
	"Harjot",
	"Jaskaran",
	"Manraj",
	"Prabhleen",
	"Sukhman",
	"Tajinder",
	"Yuvraj",
	"Guneet",
	"Harleen",
	"Jasnoor",
	"Karamjit",
	"Navleen",
	"Prabhdeep",
	"Ravneet",
	"Simarjeet",
	"Taranpreet",
	"Akalpreet",
	"Balraj",
	"Charanpreet",
	"Daljeet",
	"Ekam",
	"Fateh",
	"Gurvinder",
	"Harsimran",
];

const punjabLastNames = [
	"Singh",
	"Kaur",
	"Gill",
	"Sidhu",
	"Dhillon",
	"Sandhu",
	"Grewal",
	"Brar",
	"Bajwa",
	"Mann",
	"Bhullar",
	"Cheema",
	"Randhawa",
	"Virk",
	"Saini",
	"Bains",
	"Johal",
	"Kang",
	"Khera",
	"Multani",
	"Sekhon",
	"Atwal",
	"Deol",
	"Hundal",
	"Kahlon",
	"Malhi",
	"Nijjar",
	"Pannu",
	"Rai",
	"Sohal",
	"Thind",
	"Uppal",
	"Walia",
	"Bassi",
	"Chahal",
	"Aulakh",
	"Boparai",
	"Chawla",
	"Dhot",
	"Ghotra",
	"Hayer",
	"Jandu",
	"Khatra",
	"Ladhar",
	"Mangat",
	"Nagra",
	"Puar",
	"Rupal",
	"Sangha",
	"Takhar",
	"Virdi",
	"Waraich",
	"Zaildar",
	"Dhaliwal",
	"Chhina",
	"Basra",
	"Maan",
	"Padda",
	"Riar",
];

// ─── Bihar Doctors (50) ─────────────────────────────────────────────────────

const biharCities = [
	"Patna",
	"Gaya",
	"Muzaffarpur",
	"Bhagalpur",
	"Darbhanga",
	"Purnia",
	"Arrah",
	"Begusarai",
	"Katihar",
	"Munger",
	"Chhapra",
	"Samastipur",
	"Sasaram",
	"Hajipur",
	"Dehri",
	"Siwan",
	"Motihari",
	"Nawada",
	"Bagaha",
	"Bettiah",
	"Aurangabad",
	"Buxar",
	"Jehanabad",
	"Lakhisarai",
	"Madhubani",
];

const biharFirstNames = [
	"Rajesh",
	"Sunil",
	"Anil",
	"Vivek",
	"Sanjay",
	"Manoj",
	"Priya",
	"Ritu",
	"Amit",
	"Vikram",
	"Pankaj",
	"Ashok",
	"Neeraj",
	"Deepak",
	"Rahul",
	"Ravi",
	"Anand",
	"Shashi",
	"Vinod",
	"Arvind",
	"Meena",
	"Sunita",
	"Krishna",
	"Nitin",
	"Ajay",
	"Brajesh",
	"Chandan",
	"Dilip",
	"Gopal",
	"Hemant",
	"Jitendra",
	"Kaushal",
	"Lalit",
	"Manish",
	"Navin",
	"Pramod",
	"Ranjeet",
	"Santosh",
	"Tarun",
	"Umesh",
	"Abhay",
	"Aditya",
	"Anup",
	"Bipin",
	"Chiranjit",
	"Devendra",
	"Dhiraj",
	"Gautam",
	"Harish",
	"Keshav",
	"Mahesh",
	"Mukesh",
	"Naveen",
	"Prakash",
	"Raghav",
	"Rajiv",
	"Ritesh",
	"Sachin",
	"Shivam",
	"Sudarshan",
	"Vikas",
	"Yogesh",
	"Alok",
	"Bhavesh",
	"Chhotu",
	"Dinesh",
	"Lalan",
	"Munna",
];

const biharLastNames = [
	"Kumar",
	"Prasad",
	"Singh",
	"Verma",
	"Sinha",
	"Mishra",
	"Keshri",
	"Bhagat",
	"Chandel",
	"Chourasia",
	"Kamat",
	"Karn",
	"Kesari",
	"Kewat",
	"Lohar",
	"Mallah",
	"Nishad",
	"Nonia",
	"Rajak",
	"Raut",
	"Sada",
	"Sahni",
	"Saw",
	"Sonar",
	"Thapa",
	"Vishwakarma",
	"Chaupal",
	"Halwai",
	"Kahar",
	"Kori",
	"Jha",
	"Yadav",
	"Choudhary",
	"Thakur",
	"Gupta",
	"Sharma",
	"Das",
	"Mandal",
	"Sahay",
	"Pandey",
	"Tiwari",
	"Ranjan",
	"Ojha",
	"Dubey",
	"Rai",
	"Chaurasiya",
	"Paswan",
	"Mahto",
	"Bhushan",
	"Narayan",
	"Srivastava",
	"Pathak",
	"Lal",
	"Bharti",
];

// ─── Rest of India Doctors (100) ────────────────────────────────────────────

const indiaCities: [string, string][] = [
	["Mumbai", "Maharashtra"],
	["Delhi", "Delhi"],
	["Bangalore", "Karnataka"],
	["Hyderabad", "Telangana"],
	["Chennai", "Tamil Nadu"],
	["Kolkata", "West Bengal"],
	["Pune", "Maharashtra"],
	["Ahmedabad", "Gujarat"],
	["Jaipur", "Rajasthan"],
	["Lucknow", "Uttar Pradesh"],
	["Bhopal", "Madhya Pradesh"],
	["Nagpur", "Maharashtra"],
	["Indore", "Madhya Pradesh"],
	["Vadodara", "Gujarat"],
	["Kochi", "Kerala"],
	["Thiruvananthapuram", "Kerala"],
	["Coimbatore", "Tamil Nadu"],
	["Visakhapatnam", "Andhra Pradesh"],
	["Chandigarh", "Chandigarh"],
	["Guwahati", "Assam"],
	["Dehradun", "Uttarakhand"],
	["Ranchi", "Jharkhand"],
	["Raipur", "Chhattisgarh"],
	["Bhubaneswar", "Odisha"],
	["Surat", "Gujarat"],
	["Mysore", "Karnataka"],
	["Mangalore", "Karnataka"],
	["Jodhpur", "Rajasthan"],
	["Udaipur", "Rajasthan"],
	["Nashik", "Maharashtra"],
	["Agra", "Uttar Pradesh"],
	["Varanasi", "Uttar Pradesh"],
	["Kanpur", "Uttar Pradesh"],
	["Prayagraj", "Uttar Pradesh"],
	["Noida", "Uttar Pradesh"],
	["Gurgaon", "Haryana"],
	["Faridabad", "Haryana"],
	["Shimla", "Himachal Pradesh"],
	["Jammu", "Jammu & Kashmir"],
	["Gangtok", "Sikkim"],
	["Thane", "Maharashtra"],
	["Rajkot", "Gujarat"],
	["Madurai", "Tamil Nadu"],
	["Vijayawada", "Andhra Pradesh"],
	["Hubli", "Karnataka"],
	["Tiruchirappalli", "Tamil Nadu"],
	["Gwalior", "Madhya Pradesh"],
	["Jabalpur", "Madhya Pradesh"],
	["Aurangabad", "Maharashtra"],
	["Amravati", "Maharashtra"],
	["Navi Mumbai", "Maharashtra"],
	["Kozhikode", "Kerala"],
	["Thrissur", "Kerala"],
	["Tirupati", "Andhra Pradesh"],
	["Warangal", "Telangana"],
	["Bikaner", "Rajasthan"],
	["Kota", "Rajasthan"],
	["Salem", "Tamil Nadu"],
	["Kolhapur", "Maharashtra"],
	["Silchar", "Assam"],
	["Imphal", "Manipur"],
	["Shillong", "Meghalaya"],
	["Aizawl", "Mizoram"],
	["Dimapur", "Nagaland"],
	["Agartala", "Tripura"],
	["Itanagar", "Arunachal Pradesh"],
	["Panaji", "Goa"],
	["Pondicherry", "Puducherry"],
	["Cuttack", "Odisha"],
	["Bilaspur", "Chhattisgarh"],
];

const indiaFirstNames = [
	"Pradeep",
	"Ramesh",
	"Suresh",
	"Anjali",
	"Swati",
	"Rohan",
	"Pooja",
	"Arjun",
	"Neha",
	"Kiran",
	"Vishal",
	"Anita",
	"Mohit",
	"Shreya",
	"Akash",
	"Divya",
	"Rakesh",
	"Kavita",
	"Nikhil",
	"Pallavi",
	"Gaurav",
	"Sneha",
	"Varun",
	"Megha",
	"Siddharth",
	"Tanvi",
	"Abhishek",
	"Isha",
	"Kunal",
	"Ritika",
	"Ashwin",
	"Bhavna",
	"Chirag",
	"Darshan",
	"Esha",
	"Farhan",
	"Garima",
	"Harsh",
	"Ishaan",
	"Jatin",
	"Komal",
	"Lakshmi",
	"Manas",
	"Naveen",
	"Om",
	"Preeti",
	"Rajan",
	"Sahil",
	"Tara",
	"Ujjwal",
	"Vandana",
	"Yash",
	"Zubin",
	"Aarav",
	"Bharat",
	"Chandni",
	"Dinesh",
	"Ekta",
	"Falguni",
	"Gagan",
	"Amitabh",
	"Anupam",
	"Bhaskar",
	"Chetan",
	"Dev",
	"Eknath",
	"Ganesh",
	"Hemal",
	"Irfan",
	"Javed",
	"Karthik",
	"Lokesh",
	"Mahadev",
	"Narasimha",
	"Prithvi",
	"Qadir",
	"Rituraj",
	"Sameer",
	"Tejas",
	"Uday",
	"Vivekanand",
	"Wasim",
	"Yogendra",
	"Zeeshan",
	"Ayesha",
	"Farida",
	"Heena",
	"Jasmin",
	"Khushi",
	"Lata",
	"Meher",
	"Nagma",
	"Parul",
	"Razia",
	"Saba",
	"Tasneem",
	"Uzma",
];

const indiaLastNames = [
	"Sharma",
	"Patel",
	"Reddy",
	"Nair",
	"Rao",
	"Iyer",
	"Menon",
	"Desai",
	"Joshi",
	"Kulkarni",
	"Pillai",
	"Mukherjee",
	"Banerjee",
	"Chatterjee",
	"Sen",
	"Bose",
	"Hegde",
	"Shetty",
	"Agarwal",
	"Malhotra",
	"Kapoor",
	"Mehta",
	"Shah",
	"Chauhan",
	"Rathore",
	"Thakkar",
	"Parekh",
	"Naidu",
	"Chand",
	"Varma",
	"Bhatt",
	"Saxena",
	"Gokhale",
	"Kamath",
	"Nambiar",
	"Subramaniam",
	"Venkatesh",
	"Krishnamurthy",
	"Das",
	"Bhat",
	"Acharya",
	"Borkar",
	"Choudhury",
	"Dutta",
	"Fernandes",
	"Gaikwad",
	"Ghosh",
	"Hiremath",
	"Jagtap",
	"Kadam",
	"Kale",
	"Kashyap",
	"Kothari",
	"Mahajan",
	"Naik",
	"Nayak",
	"Purohit",
	"Qureshi",
	"Sengupta",
	"Talwar",
	"Upadhyay",
	"Vasudevan",
	"Wagh",
	"Yadav",
	"Zaveri",
	"Ansari",
	"Bari",
	"Chishti",
	"Farooqi",
	"Hussain",
	"Khan",
	"Mirza",
	"Pathan",
	"Siddiqui",
	"Syed",
];

// ─── Phone number helper ────────────────────────────────────────────────────

function generatePhone(seed: number): string {
	const prefixes = [
		"70",
		"72",
		"73",
		"74",
		"75",
		"76",
		"77",
		"78",
		"79",
		"80",
		"81",
		"82",
		"83",
		"84",
		"85",
		"86",
		"87",
		"88",
		"89",
		"90",
		"91",
		"92",
		"93",
		"94",
		"95",
		"96",
		"97",
		"98",
		"99",
		"62",
		"63",
		"64",
		"65",
		"66",
		"67",
		"68",
		"69",
		"71",
		"72",
		"73",
		"74",
		"75",
		"76",
		"77",
		"78",
		"79",
		"80",
		"81",
		"82",
		"83",
		"84",
		"85",
		"86",
		"87",
		"88",
		"89",
		"90",
		"91",
		"92",
		"93",
		"94",
		"95",
		"96",
		"97",
		"98",
		"99",
	];
	const prefix = prefixes[seed % prefixes.length];
	const suffix = String(10000000 + ((seed * 7919 + 104729) % 90000000)).slice(0, 8);
	return `+91 ${prefix}${suffix}`;
}

// ─── Generator ──────────────────────────────────────────────────────────────

interface CityEntry {
	city: string;
	state: string;
}

function generateDoctors(
	count: number,
	firstNames: string[],
	lastNames: string[],
	cities: CityEntry[],
	offset: number
): DoctorSeed[] {
	const docs: DoctorSeed[] = [];
	const usedNames = new Set<string>();
	const usedEmails = new Set<string>();

	let fi = 0;
	let li = 0;
	let suffix = 0;

	for (let i = 0; i < count; i++) {
		const idx = offset + i;

		// Generate a unique name
		let firstName: string;
		let lastName: string;
		let fullName: string;
		do {
			firstName = firstNames[fi % firstNames.length];
			lastName = lastNames[li % lastNames.length];
			fullName = `Dr. ${firstName} ${lastName}`;
			li++;
			if (li % lastNames.length === 0) {
				fi++;
				if (fi % firstNames.length === 0 && li % lastNames.length === 0) {
					suffix++;
				}
			}
			if (suffix > 0) {
				fullName = `Dr. ${firstName} ${lastName} ${suffix > 1 ? suffix : "Jr."}`;
			}
		} while (usedNames.has(fullName));
		usedNames.add(fullName);

		const spec = specializations[i % specializations.length];
		const cityEntry = cities[i % cities.length];
		const experience = 3 + (idx % 28); // 3–30 years
		const fee = 300 + ((idx * 47) % 2200); // ₹300–₹2500
		const rating = Math.round((3.0 + ((idx * 31) % 21) / 10) * 10) / 10; // 3.0–5.0

		// Pick a bio variant based on index for variety
		const variants = bioVariants[spec] || [`Experienced ${spec.toLowerCase()} providing quality healthcare.`];
		const bio = variants[i % variants.length];

		// Generate unique email
		const emailName = `${firstName.toLowerCase()}.${lastName.toLowerCase()}`;
		let email = `${emailName}@niraksh.ai`;
		let emailSuffix = 1;
		while (usedEmails.has(email)) {
			email = `${emailName}${emailSuffix}@niraksh.ai`;
			emailSuffix++;
		}
		usedEmails.add(email);

		docs.push({
			name: fullName,
			specialization: spec,
			qualification: (qualificationVariants[spec] || ["MBBS"])[i % (qualificationVariants[spec]?.length || 1)],
			experienceYears: experience,
			consultationFee: Math.round(fee / 50) * 50,
			rating,
			city: cityEntry.city,
			state: cityEntry.state,
			bio,
			contactInfo: email,
			phone: generatePhone(idx),
			isAvailable: idx % 7 !== 0, // ~85% available
		});
	}
	return docs;
}

// ─── Main ───────────────────────────────────────────────────────────────────

async function main() {
	console.log("Clearing ALL existing doctors...");
	await prisma.doctor.deleteMany();

	const punjabCityEntries: CityEntry[] = punjabCities.map((c) => ({ city: c, state: "Punjab" }));
	const biharCityEntries: CityEntry[] = biharCities.map((c) => ({ city: c, state: "Bihar" }));
	const indiaCityEntries: CityEntry[] = indiaCities.map(([city, state]) => ({ city, state }));

	const punjabDoctors = generateDoctors(150, punjabFirstNames, punjabLastNames, punjabCityEntries, 0);
	const biharDoctors = generateDoctors(100, biharFirstNames, biharLastNames, biharCityEntries, 100);
	const indiaDoctors = generateDoctors(300, indiaFirstNames, indiaLastNames, indiaCityEntries, 150);

	const allDoctors = [...punjabDoctors, ...biharDoctors, ...indiaDoctors];

	console.log(`Seeding ${allDoctors.length} doctors...`);
	console.log(`  Punjab: ${punjabDoctors.length}`);
	console.log(`  Bihar: ${biharDoctors.length}`);
	console.log(`  Rest of India: ${indiaDoctors.length}`);

	const result = await prisma.doctor.createMany({ data: allDoctors });
	console.log(`\nSuccessfully seeded ${result.count} doctors.`);

	// Quick stats
	const stats = await prisma.doctor.groupBy({
		by: ["state"],
		_count: { id: true },
		orderBy: { _count: { id: "desc" } },
	});
	console.log("\nDoctors by state:");
	for (const s of stats) {
		console.log(`  ${s.state}: ${s._count.id}`);
	}
}

main()
	.catch((e) => {
		console.error(e);
		process.exit(1);
	})
	.finally(async () => {
		await prisma.$disconnect();
	});
