import PDFDocument from "pdfkit";
import logger from "../config/logger";

interface LabReportComponent {
	componentName: string;
	observedValue: number | null;
	observedRaw: string | null;
	unit: string | null;
	referenceMin: number | null;
	referenceMax: number | null;
	status: string;
}

interface LabReportForPDF {
	id: string;
	fileName: string;
	overallSummary: string | null;
	overallRisk: string;
	abnormalCount: number;
	totalCount: number;
	createdAt: Date;
	components: LabReportComponent[];
}

/**
 * Formats a date to a readable string
 */
function formatDate(date: Date): string {
	return new Intl.DateTimeFormat("en-US", {
		year: "numeric",
		month: "long",
		day: "numeric",
	}).format(date);
}

/**
 * Generates a PDF buffer for a lab report
 */
export async function generateLabReportPDF(report: LabReportForPDF): Promise<Buffer> {
	return new Promise((resolve, reject) => {
		try {
			const doc = new PDFDocument({ margin: 50, size: "A4" });
			const chunks: Buffer[] = [];

			doc.on("data", (chunk: Buffer) => chunks.push(chunk));
			doc.on("end", () => resolve(Buffer.concat(chunks)));
			doc.on("error", (err: Error) => {
				logger.error({ err, reportId: report.id }, "PDF generation error");
				reject(err);
			});

			// Header
			doc.fontSize(24).font("Helvetica-Bold").text("Lab Report Analysis", { align: "center" });
			doc.moveDown(0.5);

			// Report metadata
			doc.fontSize(10).font("Helvetica");
			doc.text(`Report Date: ${formatDate(report.createdAt)}`, { align: "center" });
			doc.text(`File: ${report.fileName}`, { align: "center" });
			doc.moveDown(1);

			// Summary section
			doc.fontSize(14).font("Helvetica-Bold").text("Summary");
			doc.moveDown(0.3);
			doc.fontSize(10).font("Helvetica");
			doc.text(`Overall Risk: ${report.overallRisk.toUpperCase()}`);
			doc.text(`Abnormal Components: ${report.abnormalCount} of ${report.totalCount}`);
			doc.moveDown(0.5);

			if (report.overallSummary) {
				doc.fontSize(10).text(report.overallSummary, {
					align: "justify",
					lineGap: 2,
				});
			}
			doc.moveDown(1);

			// Components table header
			doc.fontSize(14).font("Helvetica-Bold").text("Lab Components");
			doc.moveDown(0.5);

			// Table configuration
			const tableTop = doc.y;
			const colWidths = [140, 80, 70, 70, 80];
			const headers = ["Component", "Observed", "Ref Min", "Ref Max", "Status"];

			// Draw table headers
			doc.fontSize(9).font("Helvetica-Bold");
			let xPos = 50;
			headers.forEach((header, i) => {
				doc.text(header, xPos, tableTop, {
					width: colWidths[i],
					align: i === 0 ? "left" : "center",
				});
				xPos += colWidths[i];
			});

			// Draw header underline
			doc.moveTo(50, tableTop + 12)
				.lineTo(50 + colWidths.reduce((a, b) => a + b, 0), tableTop + 12)
				.stroke();

			doc.moveDown(0.8);
			doc.font("Helvetica");

			// Draw table rows
			for (const component of report.components) {
				const y = doc.y;

				// Check if we need a new page
				if (y > 700) {
					doc.addPage();
					doc.y = 50;
				}

				xPos = 50;

				// Component name
				doc.fontSize(8).text(component.componentName, xPos, doc.y, {
					width: colWidths[0],
					align: "left",
				});

				// Observed value
				const observedText = component.observedRaw
					? `${component.observedRaw}${component.unit ? " " + component.unit : ""}`
					: "N/A";
				doc.text(observedText, xPos + colWidths[0], y, {
					width: colWidths[1],
					align: "center",
				});

				// Reference min
				doc.text(component.referenceMin?.toString() || "N/A", xPos + colWidths[0] + colWidths[1], y, {
					width: colWidths[2],
					align: "center",
				});

				// Reference max
				doc.text(
					component.referenceMax?.toString() || "N/A",
					xPos + colWidths[0] + colWidths[1] + colWidths[2],
					y,
					{
						width: colWidths[3],
						align: "center",
					}
				);

				// Status
				doc.text(
					component.status.toUpperCase(),
					xPos + colWidths[0] + colWidths[1] + colWidths[2] + colWidths[3],
					y,
					{
						width: colWidths[4],
						align: "center",
					}
				);

				doc.moveDown(0.8);
			}

			// Footer
			doc.moveDown(2);
			doc.fontSize(8).font("Helvetica").text("Generated by Niraksh Guardian", { align: "center" });
			doc.text(`Report ID: ${report.id}`, { align: "center" });

			doc.end();
		} catch (error) {
			logger.error({ err: error, reportId: report.id }, "Failed to generate PDF");
			reject(error);
		}
	});
}
